name: Multi Job Workflow
on: 
 - workflow_dispatch    # manual trigger
# - push  # on push it will trigger
jobs:
  test:     # checking code
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "checking code"
      - name: welcome
        run: echo "welcome to First-Job"   # manual shell commands
  build:   # converting human readable code to machine readable code
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: build
        run: echo "build is done"
      - name: welcome
        run: echo "welcome to First-Job"
  deploy:   # deploying artifacts to server
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployed in server"
      - name: welcome
        run: echo "welcome to First-Job"
