name: Multi Job Workflow
on: 
 - workflow_dispatch    # manual trigger
# - push  # on push it will trigger
jobs:
  test:     # checking code
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "checking code"
      - name: welcome
        run: sleep 10   # manual shell commands
  build:   # converting human readable code to machine readable code
    runs-on: ubuntu-latest
    needs: test
    if: success()    # if test/previous job executes successfully then only it will run this job
    steps:
      - name: build
        run: echo "build is done"
      - name: welcome
        run: sleep 10
  deploy:   # deploying artifacts to server
    runs-on: ubuntu-latest
    needs: 
      - build
      - PublishTestResult
    if: always()
    steps:
      - name: deploy
        run: echo "deployed in server"
      - name: welcome
        run: sleep 10
  PublishTestResult:   # sends test results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Notification
        run: echo "Test job completed
      - name: welcome
        run: sleep 10
