name: Runners Demo
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: OS Info
        run: cat /etc/os-release
      - name: Installed Softwares
        run: |
          java --version
          node -v
          python version
          docker version
  job2:
    runs-on: ubuntu-22.04
    steps:
      - name: Ubuntu OS Info
        run: cat /etc/os-release
